### ISSUE TITLE
Maquette pages Event (FaceToFace)

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#24]
Établir des maquettes pour les pages Event suivantes : 
- Listing des événements proposés à l'utilisateur
- Page de détail d'un événement (photo, description, relations participantes...)
- Page de notation d'un partenaire (étoiles ? notes ? checker les gems existants)
- Page de recherche d'un profil (formulaire avec critères)

**Comment by shrolox** [comment]
La maquette est faite, mais le cahier des charges était assez vague au niveau des fonctionnalités. J'ai essayé de mettre ce qui me paraissait logique. Dites moi si y'a des trucs à changer SVP

**Comment by Aeradriel** [comment]
C'est pas mal je trouve.

**Comment by Aeradriel** [comment]
Tu peux passer sur le dev de cette page.

**Comment by shrolox** [comment]
Ouaip je m'y met

**Comment by Aeradriel** [comment]
Si tu peux juste avant t'occuper du ticket sur le bug de typo sur les boutons ce serait nice.

**Comment by shrolox** [comment]
OK mais je viens de me rendre compte que je faisais la même chose que serkan en fait Oo vu qu'il n'y a pour l'instant qu'une seule page envent

**Comment by Aeradriel** [comment]
Normal qu'il y en ai qu'une les autre sont pas faites -_-

**Comment by shrolox** [comment]
Ok mais ça va bien être une page complète par type d'évent au final ? Parce qu'il y a un bouton pour sélectionner le type d'évent qui suggère le contraire

**Comment by Aeradriel** [comment]
Oui

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by anthemish** [comment]
Je close l'issue car la page est créée, on en ouvrira d'autres liées aux ≠ améliorations/problèmes de la page s'il faut.
