### ISSUE TITLE
Maquette pages Event (GroupEvent)

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#25]
Établir des maquettes pour les pages Event suivantes :

- Listing des événements proposés à l'utilisateur
- Page de détail d'un événement (photo, description, relations participantes...)
- Page de notation d'un événement/organisateur (étoiles ? notes ? checker les gems existants)

**Comment by serkansahin** [comment]
Bon alors il me faudrait de grosses infos concernant cette partie du projet. Dois-je uniquement développer la structure (design) seulement ou bien toucher aussi au back-end ? Si seulement la structure est-ce que je pourrai avoir toutes les infos concernant les ressources (noms des models etc) pour pouvoir les utiliser (genre un petit docx/pdf résumant briévement qu'est-ce qui est quoi) ? Voilà j'attends ton retour Thib' !

**Comment by Aeradriel** [comment]
Il s'agit bien juste de développer la structure. Au final il faut faire comme pour les modules de la homre; Un truc en dur que je dynamiserai par la suite. Je vois pas en quoi tu as besoin du nom des models. Et si tu en as besoin, ils sont dans app/models et on des noms très explicite. :)

**Comment by serkansahin** [comment]
![event_info](https://cloud.githubusercontent.com/assets/9954851/5887980/d0c0082c-a3ec-11e4-8b87-830f36c9c16d.png)
![event_user](https://cloud.githubusercontent.com/assets/9954851/5887979/d0b2f394-a3ec-11e4-9f09-9a59106e1ae7.png)
![viewnormal](https://cloud.githubusercontent.com/assets/9954851/5887978/d0b23af8-a3ec-11e4-90d4-f59a01dd230f.png)

J'ai avancé sur la page des listes events de groupe, il reste beaucoup à faire. Surtout que tout est static. Je post quelques screens pour te faire une idée.

**Comment by shrolox** [comment]
Je tombe sur ce post, et pour le listing des évents je t'invite à regarder la maquette que j'ai faite pour les évents face to face. On y voit que les évents sont listés avec leur "carte" organisée différemment d'un tableau, pour que ça fasse moins fichier excel :P

**Comment by serkansahin** [comment]
J'ai vu oui, je pense quand dans la logique le front-end de nos deux modules devraient être les mêmes pour avoir un contenu homogène. Donc il faut que je mette à jour le pdf de la maquette et voir si les autres sont d'accords mais je pense qu'il n'y aura pas de problème là dessus.

**Comment by anthemish** [comment]
OK pour moi :)

**Comment by serkansahin** [comment]
Thibaut peux tu me créer une page dédiée pour ce module ? Merci.

**Comment by serkansahin** [comment]
Au vu des changements concernant cette maquette (que j'ai su il y a 2 jours). J'ai fait une nouvelle maquette. https://drive.google.com/#folders/0ByZcypT-cvT6RmJvSGcyTk14TlE

**Comment by serkansahin** [comment]
Push sur la branche "groupevent", je continuerai ce weekend et sera rendu et fini avant dimanche soir.

Voici un aperçu après quelques heures de taf (ce n'est pas encore très beau).

![screencapture-127-0-0-1-3000-events](https://cloud.githubusercontent.com/assets/9954851/6312586/926d72d8-b97e-11e4-909d-3591120dc9f2.png)

J'attends la création d'une page dédiée, j'ai mis sur la page de recherche d'évent en attendant vu qu'il n'y avait pas grand chose dessus.

**Comment by Aeradriel** [comment]
On verra ce que ça donne quand ça aura avancé. :)
Route créée : /events/groupevents.

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by serkansahin** [comment]
Grosse update, liste des participants (en dur) ajouté, il faut automatiser le tout. J'ai add le responsive sur la bannière + titres (un scroll apparait je pourrai add du JS pour que éviter ça). Les détails des events sont aussi add mais en dur. En gros, il reste surtout à automatiser tout ça. Il reste encore quelques trucs à faire.

**Comment by Aeradriel** [comment]
Screen ? :)

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by serkansahin** [comment]
![screen2](https://cloud.githubusercontent.com/assets/9954851/6314820/e2bf5606-b9ed-11e4-826a-c5153d2c2a9a.png)

**Comment by serkansahin** [comment]
Des scrollers auto sont déjà en place si les listes sont trop longues, ça évite d'agrandir bêtement les div à l'infini.

**Comment by Aeradriel** [comment]
Mais niveau design ça va rester comme ça ?

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by serkansahin** [comment]
Non, je vais changer les couleurs pour que ça soit en harmonie avec la charte graphique, après je pense rester sur la même disposition, ne pas rajouter de bordure car c'est démodé. Mais si tu as des envies dis le moi :).

**Comment by Aeradriel** [comment]
Atm j'ai pas vraiment d'idée mais la c'est juste de carré quoi ^^'

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by serkansahin** [comment]
Oui, bah écoute je vais rendre plus beau tout ça, tu peux commencer à automatiser quand tu veux et en plus si il y a soucis je serais au courant.

**Comment by serkansahin** [comment]
Moyen que tu me fasses une page pour la notation de l'event/user stp :) ?

**Comment by Aeradriel** [comment]
Je fais ça.

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by serkansahin** [comment]
Yop, j'ai toujours pas de page(s) pour la notation de l'event terminé et de son organisateur, malgré le fait d'avoir pull (10:50 UTC+1).

**Comment by Aeradriel** [comment]
Done

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by serkansahin** [comment]
Push pour la notation des events/users ("/events/groupevents"). Il y a le système de notation à coder JScript/Ajax peu importe, j'ai mis des variables en dur.

![notation](https://cloud.githubusercontent.com/assets/9954851/6339039/790c9436-bbb3-11e4-95d9-72f872b9eebc.png)
![popin](https://cloud.githubusercontent.com/assets/9954851/6339041/7c29bcca-bbb3-11e4-91eb-54186051ab38.png)

La popin est complètement responsive.
![ddd](https://cloud.githubusercontent.com/assets/9954851/6339062/a56a73c2-bbb3-11e4-973c-760d52f64d9f.png)

**Comment by serkansahin** [comment]
Ah oui j'ai zappé, j'ai fait une update du CSS pour la liste des events auxquels le user est inscrit, je te laisse voir.

**Comment by Aeradriel** [comment]
Nice :)

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by anthemish** [comment]
Ca rend bien tout ça. 

Pour le TA2 je suggère de créer des events un peu plus sérieux pour le moment de la démo ceci dit ;)

**Comment by anthemish** [comment]
Je close l'issue car la page est créée, on en ouvrira d'autres liées aux ≠ améliorations/problèmes de la page s'il faut.
