### ISSUE TITLE
CSS pour le switcher de langue

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#30]
Css pour le switcher de langue (sans tout casser svp).

**Comment by serkansahin** [comment]
Oki doki !

**Comment by serkansahin** [comment]
![switcher](https://cloud.githubusercontent.com/assets/9954851/5751667/84573b0e-9c67-11e4-95cb-7ebac372554a.png)

Dis moi est-ce que c'est normal que le switcher n'affiche rien ? N'y avait-il pas l'espagnol et l'anglais en plus ?

**Comment by Aeradriel** [comment]
Si tu es en local. Tu n'as probablement pas de pays marqué comme "available". Tu peux passer available=true sur un pays avec la console rails.

**Comment by serkansahin** [comment]
Comment puis-je voir si un pays est marqué comme dispo ou non ?

**Comment by Aeradriel** [comment]
Tu peux utiliser rails console.
Un truc beau. Au moins pas dégueu. A toi de voir.

**Comment by Aeradriel** [comment]
So ?

**Comment by serkansahin** [comment]
J'avais donné prio sur le module Event, je suis de nouveau dessus. Par contre ce que je ne capte pas c'est pourquoi sur la version online le CSS est totalement différent que ce moi j'ai offline ? Bon après ça ne change pas grand chose au résultat mais c'est tout de même weird.
![diff_online_offline](https://cloud.githubusercontent.com/assets/9954851/5992343/eb0408fc-aa25-11e4-8ffa-97bd07e5d27e.png)

**Comment by serkansahin** [comment]
![screencapture-127-0-0-1-3000](https://cloud.githubusercontent.com/assets/9954851/6108842/9c588f50-b076-11e4-82e3-e5241f900b3a.png)

Pour le bouton ça va ? J'ai laissé juste le drapeau (il est centré), il y a un hover blanc aussi quand on passe la souris par dessus ca fait un petit carré autour. Il me reste le dropmenu à faire.

**Comment by serkansahin** [comment]
Hover modifié, petit effet de reduction de l'icone de drapeau quand on passe le curseur dessus (c'est stylé).

**Comment by Aeradriel** [comment]
Ben faut pas supprimé le nom de la langue...

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

**Comment by serkansahin** [comment]
Mouais ok, enfin j'ai hésité sachant que j'ai demandé à des personnes hors EIP de me donner leurs avis, ils préféraient sans le texte. Fin bref je remet ça.

**Comment by serkansahin** [comment]
![news](https://cloud.githubusercontent.com/assets/9954851/6113461/e2945794-b097-11e4-85d8-f31de1e077ef.png)

**Comment by Aeradriel** [comment]
Pour moi c'est ok


Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

2015-02-09 14:11 GMT-05:00 serkansahin <notifications@github.com>:

**Comment by anthemish** [comment]
OK aussi pas de problème

**Comment by serkansahin** [comment]
Le design du bouton est sur la branche "langselector".

**Comment by Aeradriel** [comment]
Ok cool, pensez à faire une pr.

**Comment by Aeradriel** [comment]
C'est pas ok ça pour moi....

![capture d ecran 2015-02-13 a 01 51 34](https://cloud.githubusercontent.com/assets/5124785/6183408/f6e9f5c2-b322-11e4-90b8-f3192a32dbe0.png)

**Comment by Aeradriel** [comment]
Sur le serveur c'est pas pareil mais dégueu aussi.

**Comment by serkansahin** [comment]
J'ai exactement le même problème en local, je ne sais pas pourquoi il agrandi les icônes (wtf), c'est ce que j'essaye de régler depuis hier.

**Comment by serkansahin** [comment]
J'ai push une update pour le dropdown-menu, les icônes sont à la même taille que celui de la navbar, j'ai centré le texte au milieu de la case. Par contre sur le serveur ça risque de remettre le bouton dégueulasse, je ne sais vraiment pas pourquoi ça fait ça. J'avais remarqué le soucis avant de commencer le travail dessus, le css était différent sur les 2 versions (online/offline) alors que c'était le même code. Regarde plus haut dans mes commentaires j'ai un screenshot d'avant mon taf, je pensais que ça serait réglé en refaisant un nouveau code CSS pour le bouton mais au final non c'est même plus moche...

**Comment by serkansahin** [comment]
UPDATE: Pushed on langselector

**Comment by Aeradriel** [comment]
Si c'est fini fais une pull request please.

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

2015-02-15 12:45 GMT-05:00 serkansahin <notifications@github.com>:

**Comment by serkansahin** [comment]
![newlanguage](https://cloud.githubusercontent.com/assets/9954851/6318545/a5034114-ba98-11e4-91a0-33e3f5756dcf.png)

**Comment by Aeradriel** [comment]
Ok
