### ISSUE TITLE
responsive menu bar

### ISSUE THREAD

**Issue by shrolox** [Aeradriel/birdl#33]
J'ai appris à faire une barre de menu responsive avec bootstrap et comme c'est pas le cas actuellement je me propose.

**Comment by anthemish** [comment]
Référence à la barre de navigation statique qu'on a en haut de chaque page c'est bien ça ?

Si oui, j'avais également pensé à mettre un bouton qui permet de la découvrir/cacher pour gagner en place sur l'écran. Que toi penser ?

Bonne idée en tout cas

**Comment by shrolox** [comment]
C'est ce que j'ai fait. Je l'ai commit déjà ;)
