### ISSUE TITLE
Barre de menu page de login

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#40]
Supprimer la barre du haut qui fait tâche. 

-> Déplacer le sélecteur de langue dans la page
-> Rajouter un lien login en dessous du formulaire.

**Comment by anthemish** [comment]
C'est toi Thib qui avait créé la barre de menu à l'origine ?

Sinon je pense qu'il serait intéressant de l'enlever de toutes les pages, et à la place mettre un joli bouton style transparent qui pourrait ouvrir la barre de menu latéralement par exemple. Et garder le sélecteur de langue dans un coin de l'écran, mais qu'il ne soit plus dans la barre.

**Comment by Aeradriel** [comment]
Un bouton pour ouvrir le menu c'est juste par ergo du tout.

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

Le 27 février 2015 00:05, Alexis Nasselevitch <notifications@github.com> a
écrit :

**Comment by Aeradriel** [comment]
Où en est-on ?
