### ISSUE TITLE
Omniauth - Page de validation de la date de naissance

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#42]
Design de la page pour permettre à l'utilisateur de renseigner son âge lors de la connexion avec Facebook/Google.

**Comment by Aeradriel** [comment]
Où en est-on ?

**Comment by Aeradriel** [comment]
Up, j'assigne à Alexis qui est maintenant en charge du design.

**Comment by anthemish** [comment]
Une pop-up simple de la sorte http://tinyurl.com/omniauth me semble adapté

**Comment by Aeradriel** [comment]
Ok, faut rajouter le pays.

Thibaut Roche,
Etudiant en informatique,
5ème année à {EPITECH} Paris

2015-06-13 12:10 GMT+02:00 Alexis Nasselevitch <notifications@github.com>:
