### ISSUE TITLE
Régler l'image pour qu'elle prenne tout l'écran. Page de login

### ISSUE THREAD

**Issue by XxexperxX** [Aeradriel/birdl#43]
![capture d ecran 2015-02-21 a 20 53 26](https://cloud.githubusercontent.com/assets/7129022/6317022/c3f03bb4-ba0b-11e4-9a10-66e03a962e96.png)

**Comment by XxexperxX** [comment]
On a une bande blanche au bas de l'image :)

**Comment by anthemish** [comment]
Oui j'avais vu aussi une fois mis en plein écran sur le mac par la suite, c'est déjà réglé en local ça vient avec le prochain commit

**Comment by Aeradriel** [comment]
Nice, peu importe la taille de l'écran ?

**Comment by anthemish** [comment]
Testé sur le mac avec Chrome/Safari/Firefox, que je passe en plein écran ou mode "classique" le fond prend toute la page.

**Comment by Aeradriel** [comment]
Nice. :)
Agrandis ta fenêtre au delà de la taille de ton écran (agrandis puis
déplace pour agrandir encore plus) pour être sûr. :)

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

2015-02-23 0:04 GMT-05:00 Alexis Nasselevitch <notifications@github.com>:
