### ISSUE TITLE
[Event search] Recherche rapide

### ISSUE THREAD

**Issue by anthemish** [Aeradriel/birdl#55]
* Régler le bug d'affichage sur Safari

* CSS qui saute lorsque le "Oui" ne fait pas 3 lettres (vu sur Chrome)

* ~~Associer le type d'événement à la recherche rapide~~

* Display the other parameters if one's click on a button ?

Édité par le super modérateur trop moche qui s'appelle Thibaut (et 3 fois pour spam Alexis)

**Comment by Aeradriel** [comment]
Où en est-on ?

**Comment by Aeradriel** [comment]
Faudrait le faire ASAP please, j'attends ça pour implémenter la recherche.

**Comment by Aeradriel** [comment]
En fait la recherche rapide sans type d'event c'est cool, et c'est implémenté.

**Comment by anthemish** [comment]
Ben c'est ce que je voyais pour une recherche rapide oui, du coup le type d'event on le garde uniquement pour la recherche avancée, faut que je le re-déplace

![screen shot 2015-04-16 at 15 45 39](https://cloud.githubusercontent.com/assets/3812493/7174744/b66973d4-e44f-11e4-9267-a6eedbe1bff8.png)

**Comment by anthemish** [comment]
Résultat actuel en local:

![screen shot 2015-04-16 at 15 52 40](https://cloud.githubusercontent.com/assets/3812493/7174821/a3a57e2c-e450-11e4-93ce-451eb5bc309a.png)

**Comment by Aeradriel** [comment]
Yep. Faudra juste faire une page de listing générale. Tu peux commit ce que
tu as fais du coup ? Je pullerai en me levant.

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

Le 16 avril 2015 01:46, Alexis Nasselevitch <notifications@github.com> a
écrit :

**Comment by Aeradriel** [comment]
Espace un peu les champs

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

2015-04-16 1:53 GMT-04:00 Alexis Nasselevitch <notifications@github.com>:

**Comment by anthemish** [comment]
Je règle encore 2-3 trucs et je commiterai ensuite oui

**Comment by Aeradriel** [comment]
Ouaip, juste que y'ait un max de truc de commit pour 11h demain (pour moi,
soit 17h HF). Tu peux faire passer le mot please ?

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

Le 16 avril 2015 01:56, Alexis Nasselevitch <notifications@github.com> a
écrit :

**Comment by Aeradriel** [comment]
Faut rajouter un margin en bas quand on ouvre les champs avancés. Sinon c'est ok. :)

**Comment by Aeradriel** [comment]
OK
