### ISSUE TITLE
Responsivité pour le module Group Event

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl#57]
- Rendre les différentes pages du module Group Event responsives.

**Comment by Aeradriel** [comment]
Où en est-on ?

**Comment by serkansahin** [comment]
Je n'arrive pas à faire fonctionner les media queries, ça ne les reconnait pas ou ne les active pas. J'ai essayé de debug la nuit dernière durant des heures. Je vais trouver je suis dessus.

**Comment by serkansahin** [comment]
Ca avance tranquillement ça sera bientôt fini ;) 
![responsive1](https://cloud.githubusercontent.com/assets/9954851/7093870/1e634b14-dfbd-11e4-80d0-e8499afe40ee.png)

**Comment by serkansahin** [comment]
Responsivité finie sur toutes les pages
![normal](https://cloud.githubusercontent.com/assets/9954851/7104084/d481408a-e0c7-11e4-9eec-cc05eb4fa169.png)
![responsive](https://cloud.githubusercontent.com/assets/9954851/7104085/d48c71da-e0c7-11e4-96a0-e76dcb492e6d.png)

Pull Request: https://github.com/Aeradriel/birdl/pull/73

**Comment by serkansahin** [comment]
Possibilité de close l'issue merci ?
