### ISSUE TITLE
Formulaires: afficher lorsqu'on sélecte du texte

### ISSUE THREAD

**Issue by anthemish** [Aeradriel/birdl#58]
Petit problème concernant tous les formulaires actuellement: si on sélectionne du ou tout le texte déjà écrit dans un champ, la sélection ne s'affiche pas; on ne voit pas ce qu'on sélectionne.

Cela vient sûrement du fait que la couleur du "surlignage" est blanche, tout comme la couleur de fond des champs dans le formulaires.

**Comment by Aeradriel** [comment]
C'est comme ça sur tout le site.

**Comment by Aeradriel** [comment]
Up
