### ISSUE TITLE
Vue Login - Mise en place

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#62]
Faire une maquette pour la vue de login pour les application iOs et Android.

**Comment by serkansahin** [comment]
C'est noté

**Comment by serkansahin** [comment]
Rassurez moi, c'est juste un schéma/croquis hein pour le 2 Avril... Car je suis actuellement en France et je vous avoues que pour commencer le dev Android ça va être vite tendu.

**Comment by serkansahin** [comment]
Maquette Android/iOS: https://drive.google.com/drive/#folders/0Bw-mxuBLNZDuLWw0RE9kM2l1Vzg/0B6Y88BeDsW46N0JJNzBEN1lZYkU/0ByZcypT-cvT6Tjlmc25fYi0wNzA/0ByZcypT-cvT6RUJjeDlPX0J3M00

**Comment by anthemish** [comment]
J'ai refait un schéma en reprenant l'idée (Login_page.png): https://drive.google.com/drive/folders/0Bw-mxuBLNZDub2tBOGVnc1dyTG8/0Bw-mxuBLNZDuLWw0RE9kM2l1Vzg/0B6Y88BeDsW46N0JJNzBEN1lZYkU/0ByZcypT-cvT6Tjlmc25fYi0wNzA/0ByZcypT-cvT6flMtcWZUQ25ZRS1CSExxLVhKWmhLSHRjbEVocDViSW9heW1GWElMVHJTYVE

J'ai pas d'image ou de fond coloré pour ce schéma mais évidemment on va en mettre un pour la page de login.

**Comment by serkansahin** [comment]
Je suis preneur !

**Comment by Aeradriel** [comment]
Alexis, ou le FDP qui met ses images dans le mauvais sens.. ;)

C'est validé, on peut passer au développement. Essayer au maximum de mettre des images directement (en plus de celles dans le drive) pour que l'on puisse avoir un aperçu direct sans avoir à cliquer sur x liens. :)

**Comment by Aeradriel** [comment]
Ok a recréer sur les githubs ios/android
