### ISSUE TITLE
Vue Home - Mise en place

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#63]
Faire une maquette pour la vue d'accueil pour les applications iOs et Android

**Comment by CrisCR** [comment]
Maquettes home page Android upload sur le drive:
EIP->Dev->Dev-Android

**Comment by anthemish** [comment]
J'ai fait ce schéma pour la homepage en partant des images proposées:

- J'ai opté pour une seule 'zone' de menu (droite ou gauche à voir), sachant qu'idéalement si on touche le combo photo/nom d'utilisateur ça amènerait sur le profil;
- Une icône messages qui montre le nombre de nouveaux messages, pareil si on touche ça amène aux mp;
- Pour le contenu de la homepage, j'ai pensé à afficher les modules en liste, où on peut slider rapidement de haut en bas pour accéder à un aperçu d'un module, et si on touche le module en question (HoF, calendrier/events, chat online...) on accède à la page dédiée.

![homepage](https://cloud.githubusercontent.com/assets/3812493/7002425/d2ea4ae8-dc8d-11e4-897f-9a05faf91c41.PNG)

**Comment by CrisCR** [comment]
hum ouais c'est pas mal, après je sais pas si avoir les modules en slide est plus pratique que de les avoir regroupés dans un menu.

**Comment by Aeradriel** [comment]
Super maquette, bien détaillée. J'adore. Concernant les modules, avec la tailles des téléphones d'aujourd'hui, je ne pense même pas qu'il y ait besoin de scroller. Sinon on peut mettre en place un système de swipe to change. Un peu comme un carousel, en swipant l'écran sur la (ou les -si on en mets 2 l'une sous l'autre-) "zone(s) module(s)", ca changera de module. A voir ce qui est le mieux. En tout cas l'idée est validée on peut passer au dev.

**Comment by CrisCR** [comment]
Du coup on part sur quoi? Photo de profil et messages dans une barre façon Alexis ou dans un menu déroulant comme je l'ai présenté dans mes maquettes?
De même que la présentation des modules, on a 3 choix:
- Façons carrousel en swipant d'un écran à un autre
- Modules dans la même pages avec un système de scrool pour y accéder.
- Ou un menu déroulant.
Que choisir?..

**Comment by Aeradriel** [comment]
La maquette qu'il y a sur Github + modules même page pour l'instant.

**Comment by Aeradriel** [comment]
Ok a recréer sur les githubs ios/android
