### ISSUE TITLE
Vue Inscription - Mise en place

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#64]
Faire une maquette pour la page d'inscription pour les applications iOs et Android.

**Comment by anthemish** [comment]
C'est prêt ?

**Comment by shrolox** [comment]
Yep, c'est upload sur le drive

**Comment by shrolox** [comment]
Dans Conception/maquettes/mobile

**Comment by anthemish** [comment]
Ok, je regarde tout ça sous peu

**Comment by anthemish** [comment]
J'ai ajouté un détail, mettre un titre qui montre l'étape d'inscription (1/3 etc.):

![signin_page](https://cloud.githubusercontent.com/assets/3812493/7002385/15ccedb2-dc8d-11e4-9a97-80c4fd150a13.JPG)

**Comment by Aeradriel** [comment]
Très bien, c'est validé. On peut implémenter. Pom tu te charge de ça sur iOs ? Je laisse le lead dev Android assigner pour cette plateforme.
