### ISSUE TITLE
Mettre le site vitrine en ligne

### ISSUE THREAD

**Issue by anthemish** [Aeradriel/birdl#65]
Utiliser le lien fourni par le Labeip pour mettre en ligne le site vitrine (même s'il n'est pas complètement terminé):

http://eip.epitech.eu/2016/birdl

**Comment by Aeradriel** [comment]
C'est quoi ce lien ?

**Comment by anthemish** [comment]
Tu peux le trouver sur l'intra EIP quand tu accèdes à la fiche de notre EIP. En plus d'un svn/mail-list etc. chaque EIP a un lien pour mettre en ligne un site vitrine

**Comment by Aeradriel** [comment]
On a les accès ?

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris

Le 10 avril 2015 06:45, Alexis Nasselevitch <notifications@github.com> a
écrit :

**Comment by Aeradriel** [comment]
Up.

**Comment by anthemish** [comment]
Il faut push le(s) fichier(s) HTML/CSS/PHP/whatever dans le dosser www/ sur le svn et c'est bon
