### ISSUE TITLE
GroupEvents - Ajout d'une liste des événements à venir

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl#68]
- Ajout de la liste des événements à venir à côté de celles qui sont passés.

**Comment by serkansahin** [comment]
Bon j'ai un soucis vraiment relou, j'ai 2 divs contenant chacune une liste (passés & à venir). Le problème étant que la div "area" de la div des événements "à venir" viens piétiner sur celle des événements passés. Donc pas possible de cliquer sur le bouton de notation d'un évent/user... Si quelqu'un à rencontrer un problème dans ce genre je suis preneur.

![screen1](https://cloud.githubusercontent.com/assets/9954851/7007786/01b4527a-dc8d-11e4-8231-b42a794ea88c.png)

**Comment by serkansahin** [comment]
Problème résolu! Liste créée, le ticket peut être clos.

**Comment by Aeradriel** [comment]
Fais plutôt un seul bloc séparé en 2.

**Comment by Aeradriel** [comment]
J'ai rien dis, on laisse comme ça jusqu'au rework graphique.
