### ISSUE TITLE
Refaire le design des pages d'événement

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#81]
Refaire le design des pages d'événement pour coller au design général du site.

**Comment by anthemish** [comment]
J'ajoute le lien pour rappel à moi-même:

http://163.5.84.208/events/facestofaces/9

**Comment by Aeradriel** [comment]
+ Groupevent :D

Thibaut Roche,
Etudiant en informatique,
5ème année à {EPITECH} Paris

Le 20 juin 2015 12:02, Alexis Nasselevitch <notifications@github.com> a
écrit :
