### ISSUE TITLE
Ajouter le système d'ajout à une liste d'ami

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl#86]
Salut !

Alors je poste ça ici dans "Birdl" car ça concerne tout aussi bien le front-End que le Back-End (surtout ce dernier en fait). Donc tout est dans le titre, il faudrait implémenter assez rapidement le système d'ajout d'un utilisateur à sa liste d'amis (relations). En effet pour le système de messagerie, nous avons besoin d'aller chercher le user id d'un utilisateur de la plateforme, le tout manuellement car la route /api/messages/relations n'affiche rien car pas d'amis à part si on a déjà envoyé un message préalablement à quelqu'un (et ceci manuellement donc c'est bien relou).

Le but serait donc d'implémenter une option (un bouton ?) "Ajouter à mes amis" avec un système de notification (mail ? ou un message qui apparaît sur le dashboard avec un lien pour accepter ou non). Nous avons vraiment besoin de ça pour tout ce qui est messagerie et chat online (je présume). Car on peut très bien coder un backend avec des valeurs en dur (receiver_id) mais ce n'est pas le but autant ne pas faire cette fonctionnalité dans les applis alors :).

Voilà @anthemish @Aeradriel

**Comment by Aeradriel** [comment]
API : 

GET, POST, DELETE /api/user/relations

**Comment by serkansahin** [comment]
Les routes marchent parfaitement merci :)
