### ISSUE TITLE
Créer les clés de traduction du module 'Event'

### ISSUE THREAD

**Issue by Aeradriel** [Aeradriel/birdl#9]
Créer les clés de traduction du module 'Event'.

**Comment by Aeradriel** [comment]
C'est oK ?

**Comment by serkansahin** [comment]
Je relève une erreur de traduction pour la partie "GroupEvent", la clé :list_past_events contient une erreur d'orthographe en français: "...événements passées" -> "...événements passés"

**Comment by Aeradriel** [comment]
Tag Joffrey please.

Thibaut Roche,
Etudiant en informatique,
4ème année à {EPITECH} Paris
