### ISSUE TITLE
[Messages] La route /api/messages /api/messages/sent & received ne servent à rien

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl#90]
Salut,

Alors tout est dans le titre, j'ai envoyé et j'ai reçu des messages depuis mon compte et j'ai testé ces routes depuis un client REST. Résultat, ça ne m'affiche absolument rien pour /api/messages, ni pour sent ou received. Ce sont des requêtes GET donc pas de paramètres à donner.

Possibilité de m'éclairer dessus ?

Merci :)

**Comment by serkansahin** [comment]
J'ai vu que sur iOS ca marchait...par qu'elle magie ou code trixing ?

**Comment by Aeradriel** [comment]
On a juste lu ce qui a été publié sur Facebook (https://www.facebook.com/photo.php?fbid=10205599531287893&set=pcb.1623262241261975&type=3&theater). Et utilisé la route /messages..
